### ISSUE TITLE
scss template block not compiling

### ISSUE THREAD

**Issue by Popl7** [MichealPearce/sapped-svelte-ts-boilerplate#3]
hi,

I tried your template to get started with Sapper and Typescript.
It looks great!

Today I tried some scss styling in my template and I could not get it to compile.

The template contains:
```js
<style lang="scss">
.blog {
  color: red;

  &:hover {
    background: DarkCyan;
  }
}
</style>
```

and I run with `yarn dev` or `npm run dev`.

This gives an error:
```js
Identifier is expected
17:   color: red;
18:
19:   &:hover {
      ^
20:     background: DarkCyan;
21:   }
internal/modules/cjs/loader.js:1033
  throw err;
```

Is this a bug or am I doing something wrong?

**Comment by Popl7** [comment]
it seems that it does work this way with the default svelte-process package. I will try this package a bit further.

What is the reason to use `svelte-ts-preprocess` and not the default `https://github.com/sveltejs/svelte-preprocess`?

**Comment by MichealPearce** [comment]
Hi @Popl7, thank you for contributing! I don't seem to be having the same issue you're having with compiling scss, could you explain further on how and where you added the code above?

As for using `svelte-ts-preprocess` over the default: I believe the issue was it did not compile properly. I'd either have issues with VSCode not recognizing types, it not importing interfaces. This is something that should be looked into as right now it's using both preprocessors (svelte-preprocess for sass and the other for typescript) and I believe this is also effecting preloading on the server-side.

**Comment by MichealPearce** [comment]
> it seems that it does work this way with the default svelte-process package. I will try this package a bit further.
> 
> What is the reason to use `svelte-ts-preprocess` and not the default `https://github.com/sveltejs/svelte-preprocess`?

Updated to only use svelte-preprocess, let me know if there are any issues!

**Comment by Popl7** [comment]
hi Michael,

thank you for the quick reply.

I added the scss in a svelte file and I get an error about the nested pseudo-class selector (&:hover) which is not valid css.

I saw that you have similar scss now in the template now. I will try this again.

Thx

**Comment by Popl7** [comment]
the changes you made fixed it 👍 

Thanks
